### ISSUE TITLE
JoSS Review: Quality of writing

### ISSUE THREAD

**Issue by betteridiot** [babinyurii/RECAN#11]
In conjunction with the review of your package to JoSS (available at https://github.com/openjournals/joss-reviews/issues/2014), here is an issue for you to address for your submission.

This is potentially the most difficult issue to bring up. While the implementation of `recan` is tremendous work, the readability of this submission could use significant revisions.

I planned on making a series of revision notes to pass on to the author but, after looking at the list, I will refrain as I know what it feels like to have a giant list of revisions to come from a reviewer.

Generally speaking, this manuscript would benefit from improvements in grammar and sentence structure.

**Comment by babinyurii** [comment]
The paper has been edited. Perhaps, the language is a bit better now.

**Comment by babinyurii** [comment]
@whedon generate pdf

**Comment by ghost** [comment]
Hi @babinyurii,

There seems to be a missing piece between the 2nd and the 3rd sentences in your summary.

> Gaining insights into such genetic events is important for a better understanding
of viral biology. This task could be achieved through analysis of similarity plots based on
calculating genetic distances between nucleotide sequences.

I think you meant to go from `recombination events` to `recombination detection analysis` to `similarity plots`. But here, the middle link is missing. So, the logic sounds a bit odd.

I can tell there are still a few grammar mistakes in the manuscript. E.g. the article "the" is missing here and there. But I am not a native English speaker. Perhaps @betteridiot could give you more helpful comments for this.

**Comment by babinyurii** [comment]
Many thanks for this valuable comment, @lamhm. I've edited the 3rd sentence to clarify the meaning.

**Comment by betteridiot** [comment]
As it looks like you are actively working on this, I will close this issue.
