### ISSUE TITLE
Copyright statement

### ISSUE THREAD

**Issue by sikuan** [babinyurii/RECAN#14]
Hi,

I'm trying to packaging this into Debian as a Debian package, and now I'm writing the copyright information.

https://github.com/babinyurii/recan/blob/45c5a61d46924b8e6a364d318933cf2fede6e13e/LICENCE.txt#L1

I found the copyright statement in `LICENCE.txt` which seems incorrect. (`The Python Packaging Authority (PyPA)` suppose a template or placeholder?)

Could you please let me know this statement is correct or not? If not, could you please fix this?

Thank you~

**Comment by babinyurii** [comment]
Hi @sikuan !
You're right, this line is incorrect. I'll fix it in the next update.
