### ISSUE TITLE
save_data: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by JmaJeremy** [babinyurii/RECAN#17]
**Describe the bug**
When using the `save_data` method I'm getting an error saying `TypeError: 'NoneType' object is not subscriptable`

Full error:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    sim_obj.save_data(out="csv", out_name="test_data")
  File "/home/jeremy/.local/lib/python3.8/site-packages/recan/simgen.py", line 293, in save_data
    df = pd.DataFrame(data=self._distance, index=self._ticks[1:]).T
TypeError: 'NoneType' object is not subscriptable
```

**To Reproduce**
```
from recan.simgen import Simgen
sim_obj = Simgen("test.fasta")
sim_obj.save_data(out="csv", out_name="test_data")
```

**Expected behavior**
CSV file containing plot data is written

**Additional context**

**Comment by JmaJeremy** [comment]
The same error appears to occur when using the `get_data` method

This is using Python v. 3.8.5

**Comment by babinyurii** [comment]
the packege is updated now. Now one can save distance data only in the csv format.
