### ISSUE TITLE
k2p: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Zjianglin** [babinyurii/RECAN#18]
Hi developer,

I'm trying to run `recan` to detect a potential recombination event. However, after I changed the 'dist=k2p', the program crashed out. But the default `pdist` could normally run. Could you please help figure it out?

Here is the running output:
```
Traceback (most recent call last):
  File "test_recan.py", line 6, in <module>
    sim_obj.simgen(window=200, shift=20, pot_rec=1,  dist='k2p')
  File "/home/zjl/anaconda3/lib/python3.7/site-packages/recan/simgen.py", line 241, in simgen
    self._distance = self._move_window(window, pot_rec, shift, dist)
  File "/home/zjl/anaconda3/lib/python3.7/site-packages/recan/simgen.py", line 117, in _move_window
    distance = self._K2Pdistance(seq1, seq2)
  File "/home/zjl/anaconda3/lib/python3.7/site-packages/recan/simgen.py", line 153, in _K2Pdistance
    p = float(ts_count) / length
ZeroDivisionError: float division by zero
```

My MSA squences have some `N` bases and `degenerate bases`, is this the reason? How could prepare the input alignment? Thanks.

**Comment by babinyurii** [comment]
Sorry for answering so late. Problems may be caused by the gaps in the alignment. I'm preparing now update which would somehow notify the user about it if this error occurs.
If you still interested in using the package, you can give me the input file and i can figure out what caused the problem.

**Comment by babinyurii** [comment]
bug with k2p distance fixed.
