### ISSUE TITLE
JoSS Review: Example Usage

### ISSUE THREAD

**Issue by betteridiot** [babinyurii/RECAN#6]
In conjunction with the review of your package to JoSS (available at https://github.com/openjournals/joss-reviews/issues/2014), here is an issue for you to address for your submission.

While I appreciate the wealth of examples that were added to the documentation, none of these examples explain what is being visualized thoroughly. A lay-person, or early scientist in the field, may look at these plots and not understand _where_ the events are occurring and _what_ they look like. Consider adding brief annotations to the screen shots explaining what/where these events are.

**Comment by ghost** [comment]
The author should also specify how users can access the example datasets. Otherwise, the following line of code would be confusing for inexperienced users: `sim_obj = Simgen("./data/hbv_C_Bj_Ba.fasta")`.

On a side note, I guess the author have changed the name of the `data` folder in their Github repository into `datasets`. So, it may need to be changed in the example code too.

**Comment by babinyurii** [comment]
The first screenshot showing similarity plot is annotated : https://raw.githubusercontent.com/babinyurii/recan/master/pictures/HBV_1_rec_C_B_annotated.PNG

Link to the dataset folder is added to README (right before the examples), and the statement `sim_obj = Simgen("./data/hbv_C_Bj_Ba.fasta` is changed to `sim_obj = Simgen("./datasets/hbv_C_Bj_Ba.fasta`
https://github.com/babinyurii/recan

**Comment by ghost** [comment]
@babinyurii: I can see that you have updated your figures and your example code. But I do not see where you have specified the download link to your example datasets. Did you forget to push your commit?

**Comment by babinyurii** [comment]
Thanks for comment, @lamhm. Now I've added the link to download the example datasets. It's in the section `example datasets` which is right above the `references` section.

**Comment by ghost** [comment]
Thanks a lot, @babinyurii. The example usage looks great now.

@betteridiot - If you do not have any additional concerns, I think you can close this issue.
