### ISSUE TITLE
Distance Calculation

### ISSUE THREAD

**Issue by betteridiot** [babinyurii/RECAN#8]
As it stands, `simgen` only allows `pdist` and `k2p` as its distance formula, but your program doesn't allow to user to define their own: such as a Jukes-Cantor or Tajima-Nei distance.

Would it be possible to allow `simgen` to take a function as an argument for its `dist=` kwarg?

**Comment by babinyurii** [comment]
Now it's not possible to pass a function as an argument for `dist=`. I can add this feature (and other variants of distance calculations)  in the next update,

**Comment by babinyurii** [comment]
Jukes-Cantor,  Kimura 2-Parameter and Tamura distances added in the new version.
